//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;
using ECSFrenzy.Networking;


namespace ECSFrenzy.Generated
{
    [BurstCompile]
    public struct ECSFrenzyNetworkingJoinGameRequestSerializer : IComponentData, IRpcCommandSerializer<ECSFrenzy.Networking.JoinGameRequest>
    {
        public void Serialize(ref DataStreamWriter writer, in ECSFrenzy.Networking.JoinGameRequest data)
        {
        }

        public void Deserialize(ref DataStreamReader reader, ref ECSFrenzy.Networking.JoinGameRequest data)
        {
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<ECSFrenzyNetworkingJoinGameRequestSerializer, ECSFrenzy.Networking.JoinGameRequest>(ref parameters);
        }

        static PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }
    class ECSFrenzyNetworkingJoinGameRequestRpcCommandRequestSystem : RpcCommandRequestSystem<ECSFrenzyNetworkingJoinGameRequestSerializer, ECSFrenzy.Networking.JoinGameRequest>
    {
    }
}
